"""empty message

Revision ID: 09ad1f71a53c
Revises: 0bd9a98d0e14
Create Date: 2024-05-06 22:14:20.729563

"""
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa
from sqlalchemy import column, table, DateTime

# revision identifiers, used by Alembic.
revision = '09ad1f71a53c'
down_revision = '0bd9a98d0e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_time', sa.DateTime(), nullable=True, comment='过期时间'))
    # 添加完列后更新历史数据
    accounts = table('tb_account',column('expiration_time', DateTime()))

    # 计算默认过期时间：当前时间 + 30天
    thirty_days_later = datetime.now() + timedelta(days=30)

    # 更新表中所有记录
    op.execute(
        accounts.update().values(expiration_time=thirty_days_later)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.drop_column('expiration_time')

    # ### end Alembic commands ###
