"""empty message

Revision ID: 0bd9a98d0e14
Revises: d33fbd9a8ee4
Create Date: 2024-05-02 22:36:17.196639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd9a98d0e14'
down_revision = 'd33fbd9a8ee4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('UPDATE tb_token SET plus_subscription = 3 WHERE plus_subscription = 1')
    op.execute('UPDATE tb_token SET plus_subscription = 2 WHERE plus_subscription = 0')
    op.execute('UPDATE tb_token SET plus_subscription = 1 WHERE plus_subscription = -1')
    op.execute('UPDATE tb_account SET show_conversations = 0 WHERE show_conversations=\'False\'')
    op.execute('UPDATE tb_account SET show_conversations = 1 WHERE show_conversations=\'True\'')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.alter_column('show_conversations',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.alter_column('show_conversations',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
