"""empty message

Revision ID: b6957e8ddb5c
Revises: d228cc8d64ca
Create Date: 2024-04-26 19:26:22.350014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6957e8ddb5c'
down_revision = 'd228cc8d64ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpt35_limit', sa.Integer(), nullable=True, comment='GPT-3.5次数(为0无法使用，负数不限制)'))
        batch_op.add_column(sa.Column('gpt4_limit', sa.Integer(), nullable=True, comment='GPT-4.0次数(为0无法使用，负数不限制)'))
        batch_op.add_column(sa.Column('show_conversations', sa.Text(), nullable=True, comment='会话无需隔离，true:不隔离,false:隔离'))

    op.execute('UPDATE tb_account SET gpt35_limit = -1 WHERE gpt35_limit IS NULL')
    op.execute('UPDATE tb_account SET gpt4_limit = -1 WHERE gpt4_limit IS NULL')
    op.execute('UPDATE tb_account SET show_conversations = \'False\' WHERE show_conversations IS NULL')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.drop_column('show_conversations')
        batch_op.drop_column('gpt4_limit')
        batch_op.drop_column('gpt35_limit')

    # ### end Alembic commands ###
