"""empty message

Revision ID: b7dea419a240
Revises: 09ad1f71a53c
Create Date: 2024-05-09 22:56:35.751438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dea419a240'
down_revision = '09ad1f71a53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_chat', sa.Integer(), nullable=True, comment='临时聊天，1:强制使用,0:非强制使用'))

    op.execute('UPDATE tb_account SET temporary_chat = 0 WHERE temporary_chat IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.drop_column('temporary_chat')

    # ### end Alembic commands ###
