"""empty message

Revision ID: d228cc8d64ca
Revises: 
Create Date: 2024-04-19 19:32:36.964048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd228cc8d64ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_account',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('account', sa.Text(), nullable=False, comment='唯一名称'),
    sa.Column('password', sa.Text(), nullable=False, comment='密码'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态, 1:正常, 0:禁用'),
    sa.Column('token_id', sa.Integer(), nullable=False, comment='token_id'),
    sa.Column('share_token', sa.Text(), nullable=False, comment='共享token'),
    sa.Column('expire_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('password')
    )
    op.create_table('tb_token',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键'),
    sa.Column('token_name', sa.Text(), nullable=False, comment='token名称'),
    sa.Column('refresh_token', sa.Text(), nullable=False, comment='刷新token'),
    sa.Column('access_token', sa.Text(), nullable=False, comment='访问token'),
    sa.Column('expire_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_token')
    op.drop_table('tb_account')
    # ### end Alembic commands ###
