"""empty message

Revision ID: d33fbd9a8ee4
Revises: b6957e8ddb5c
Create Date: 2024-04-27 11:18:33.816290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33fbd9a8ee4'
down_revision = 'b6957e8ddb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plus_subscription', sa.Integer(), nullable=True, comment='订阅状态, -1:未知, 0:未订阅, 1:已订阅'))

    op.execute('UPDATE tb_token SET plus_subscription = -1 WHERE plus_subscription IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_token', schema=None) as batch_op:
        batch_op.drop_column('plus_subscription')

    # ### end Alembic commands ###
